package com.mg.model;

// Generated Sep 18, 2016 9:01:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MgAuditHist generated by hbm2java
 */
@Entity
@Table(name = "mg_audit_hist", schema = "bolsos")
public class AuditHist extends BasicAudit implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = 1L;

	public AuditHist() {
	}

	public AuditHist(int id) {
		this.id = id;
	}

	public AuditHist(int id, String username, String location,
			String sessionGuid, String requestGuid, Date creationDate,
			String actionUser, String outcome, String message,
			String serverName, String browser, String url, Integer callDuration) {
		setId(id);
		setUsername(username);
		setLocation(location);
		setSessionGuid(sessionGuid);
		setRequestGuid(requestGuid);
		setCreationDate(creationDate);
		setActionUser(actionUser);
		setOutcome(outcome);
		setMessage(message);
		setServerName(serverName);
		setBrowser(browser);
		setUrl(url);
		setCallDuration(callDuration);
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_audit_hist_id")
	@SequenceGenerator(name="seq_audit_hist_id", sequenceName="bolsos.seq_audit_hist_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}



}
