package com.mg.model;
// Generated Oct 22, 2017 5:40:12 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgJobs generated by hbm2java
 */
@Entity
@Table(name = "mg_config", schema = "bolsos")
public class Config implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = -1329107003221675896L;
	private int id;
	private String code;
	private String value;
	private String description;
	private Date creationDate;

	public Config() {
	}

	public Config(int id, String code) {
		this.id = id;
		this.code = code;
	}

	public Config(int id, String code, String value, String description, Date creationDate) {
		this.id = id;
		this.code = code;
		this.value = value;
		this.description = description;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_config_id")
	@SequenceGenerator(name="seq_config_id", sequenceName="bolsos.seq_config_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
