package com.mg.model;

// Generated Mar 3, 2016 12:02:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgCouponsUser generated by hbm2java
 */
@Entity
@Table(name = "mg_coupons_user", schema = "bolsos")
public class CouponsUser implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = 8576868933502464617L;
	private int id;
	private Users users;
	private Coupons coupons;
	private Date creationDate;

	public CouponsUser() {
	}

	public CouponsUser(int id, Users users, Coupons coupons) {
		this.id = id;
		this.users = users;
		this.coupons = coupons;
	}

	public CouponsUser(int id, Users users, Coupons coupons,
			Date creationDate) {
		this.id = id;
		this.users = users;
		this.coupons = coupons;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_coupons_user_id")
	@SequenceGenerator(name="seq_coupons_user_id", sequenceName="bolsos.seq_coupons_user_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", nullable = false)
	public Coupons getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Coupons coupons) {
		this.coupons = coupons;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
