package com.mg.model;

// Generated Mar 3, 2016 12:02:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.enums.CouponStatus;

/**
 * MgCoupons generated by hbm2java
 */
@Entity
@Table(name = "mg_coupons", schema = "bolsos")
public class Coupons implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = -5438196080427851267L;
	private int id;
	private CouponsType couponsType;
	private String couponName;
	private CouponStatus statusCode;
	private Date inactiveDate;
	private Date creationDate;
	private Set<CouponsUser> couponsUsers = new HashSet<CouponsUser>(0);

	public Coupons() {
	}

	public Coupons(int id, CouponsType couponsType, String couponName, CouponStatus statusCode) {
		this.id = id;
		this.couponsType = couponsType;
		this.couponName = couponName;
		this.statusCode = statusCode;
	}

	public Coupons(int id, CouponsType couponsType, String couponName,
			Date creationDate, Set<CouponsUser> couponsUsers, CouponStatus statusCode) {
		this.id = id;
		this.couponsType = couponsType;
		this.couponName = couponName;
		this.creationDate = creationDate;
		this.couponsUsers = couponsUsers;
		this.statusCode = statusCode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_coupons_id")
	@SequenceGenerator(name="seq_coupons_id", sequenceName="bolsos.seq_coupons_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_type_id", nullable = false)
	public CouponsType getCouponsType() {
		return this.couponsType;
	}

	public void setCouponsType(CouponsType couponsType) {
		this.couponsType = couponsType;
	}

	@Column(name = "coupon_name", nullable = false, length = 50)
	public String getCouponName() {
		return this.couponName;
	}

	public void setCouponName(String couponName) {
		this.couponName = couponName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupons", cascade=CascadeType.ALL)
	public Set<CouponsUser> getCouponsUsers() {
		return this.couponsUsers;
	}

	public void setCouponsUsers(Set<CouponsUser> couponsUsers) {
		this.couponsUsers = couponsUsers;
	}

	@Column(name = "status_code", nullable = false, length = 10)
	@Enumerated(EnumType.STRING)
	public CouponStatus getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(CouponStatus statusCode) {
		this.statusCode = statusCode;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inactive_date", length = 29)
	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}
}
