package com.mg.model;

// Generated 31-ene-2015 21:26:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.enums.ComponentType;

/**
 * MgCustomComponent generated by hbm2java
 */
@Entity
@Table(name = "mg_custom_component", schema = "bolsos")
public class CustomComponent implements java.io.Serializable, BasicModel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3361880719522427630L;
	private int id;
	private ComponentType typeCode;
	private String code;
	private String name;
	private Set<CustomComponentCollection> customComponentCollections = new HashSet<CustomComponentCollection>(0);
	private Date creationDate;
	
	public CustomComponent() {
	}

	public CustomComponent(int id, ComponentType typeCode, String code, String name) {
		this.id = id;
		this.typeCode = typeCode;
		this.code = code;
		this.name = name;
	}

	public CustomComponent(int id, ComponentType typeCode, String code, String name,
			Date creationDate,
			Set<CustomComponentCollection> customComponentCollections) {
		this.id = id;
		this.typeCode = typeCode;
		this.code = code;
		this.name = name;
		this.creationDate = creationDate;
		this.customComponentCollections = customComponentCollections;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_custom_component_id")
	@SequenceGenerator(name="seq_custom_component_id", sequenceName="bolsos.seq_custom_component_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type_code", nullable = false, length = 10)
	@Enumerated(EnumType.STRING)
	public ComponentType getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(ComponentType typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customComponent")
	public Set<CustomComponentCollection> getCustomComponentCollections() {
		return this.customComponentCollections;
	}

	public void setCustomComponentCollections(
			Set<CustomComponentCollection> customComponentCollections) {
		this.customComponentCollections = customComponentCollections;
	}

}
