package com.mg.model;

// Generated 29-mar-2015 3:39:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MgCustomComponentText generated by hbm2java
 */
@Entity
@Table(name = "mg_custom_component_text", schema = "bolsos", uniqueConstraints = {
		@UniqueConstraint(columnNames = "id") })
public class CustomComponentText implements java.io.Serializable, BasicModel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6899705113894691701L;
	private int id;
	private Image image;
	private Integer posTop;
	private Integer posLeft;
	private Integer width;
	private Integer height;
	private Integer imageWidth;
	private Integer imageHeight;
	private String align;
	private Integer maximum;
	private Date creationDate;

	public CustomComponentText() {
	}

	public CustomComponentText(int id,
			Image image, int posTop,
			int posLeft, int width, int height, String align) {
		this.id = id;
		this.image = image;
		this.posTop = posTop;
		this.posLeft = posLeft;
		this.width = width;
		this.height = height;
		this.align = align;
	}

	public CustomComponentText(int id,
			Image image, int posTop,
			int posLeft, int width, int height, String align, Integer maximum,
			Date creationDate) {
		this.id = id;
		this.image = image;
		this.posTop = posTop;
		this.posLeft = posLeft;
		this.width = width;
		this.height = height;
		this.align = align;
		this.maximum = maximum;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_custom_component_text_id")
	@SequenceGenerator(name="seq_custom_component_text_id", sequenceName="bolsos.seq_custom_component_text_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "image_id", nullable = false)
	public Image getImage() {
		return this.image;
	}

	public void setImage(Image image) {
		this.image = image;
	}

	@Column(name = "pos_top", nullable = false)
	public Integer getPosTop() {
		return this.posTop;
	}

	public void setPosTop(Integer posTop) {
		this.posTop = posTop;
	}

	@Column(name = "pos_left", nullable = false)
	public Integer getPosLeft() {
		return this.posLeft;
	}

	public void setPosLeft(Integer posLeft) {
		this.posLeft = posLeft;
	}

	@Column(name = "width", nullable = false)
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false)
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "align", nullable = false, length = 7)
	public String getAlign() {
		return this.align;
	}

	public void setAlign(String align) {
		this.align = align;
	}

	@Column(name = "maximum")
	public Integer getMaximum() {
		return this.maximum;
	}

	public void setMaximum(Integer maximum) {
		this.maximum = maximum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "image_width", nullable = true)
	public Integer getImageWidth() {
		return imageWidth;
	}

	public void setImageWidth(Integer imageWidth) {
		this.imageWidth = imageWidth;
	}

	@Column(name = "image_height", nullable = true)
	public Integer getImageHeight() {
		return imageHeight;
	}

	public void setImageHeight(Integer imageHeight) {
		this.imageHeight = imageHeight;
	}


}
