package com.mg.model;

// Generated Sep 18, 2016 9:01:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.entities.IDevice;
import com.mg.enums.UserActionType;

/**
 * DeviceComponentHist generated by hbm2java
 */
@Entity
@Table(name = "mg_device_component_hist", schema = "bolsos")
public class DeviceComponentHist implements java.io.Serializable, BasicModel, IDevice {

	private static final long serialVersionUID = -5344365145421486498L;
	private int id;
	private Device device;
	private CustomComponentCollection customComponentCollection;
	private UserActionType userAction;
	private Date actionDate;
	private Date creationDate;
	
	public DeviceComponentHist() {
	}

	public DeviceComponentHist(int id, Device device,
			CustomComponentCollection customComponentCollection) {
		this.id = id;
		this.device = device;
		this.customComponentCollection = customComponentCollection;
	}

	public DeviceComponentHist(int id, Device device,
			CustomComponentCollection customComponentCollection,
			Boolean added, Boolean sold, Date actionDate,
			Date creationDate) {
		this.id = id;
		this.device = device;
		this.customComponentCollection = customComponentCollection;
		this.actionDate = actionDate;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_device_component_hist_id")
	@SequenceGenerator(name="seq_device_component_hist_id", sequenceName="bolsos.seq_device_component_hist_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "component_id", nullable = false)
	public CustomComponentCollection getCustomComponentCollection() {
		return this.customComponentCollection;
	}

	public void setCustomComponentCollection(
			CustomComponentCollection customComponentCollection) {
		this.customComponentCollection = customComponentCollection;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "action_date", length = 29)
	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	
	@Enumerated(EnumType.STRING)
	@Column(name = "user_action", length = 10)
	public UserActionType getUserAction() {
		return this.userAction;
	}

	public void setUserAction(UserActionType userAction) {
		this.userAction = userAction;
	}

	@Override
	public String toString(){
		return "CCCid : " + customComponentCollection.getId() + 
			   ", Action: " + userAction.name();
	}
}
