package com.mg.model;
// Generated Nov 3, 2018 3:19:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.entities.IDeviceAddable;
import com.mg.entities.IDeviceSuggestionable;
import com.mg.util.CommonUtils;

/**
 * MgDeviceSuggestions generated by hbm2java
 */
@Entity
@Table(name = "mg_device_suggestions", schema = "bolsos")
public class DeviceSuggestions implements java.io.Serializable, BasicModel, IDeviceSuggestionable  {

	private static final long serialVersionUID = 1L;
	private int id;
	private Device device;
	private String codeSuggestion;
	private String typeSuggestion;
	private Integer countSuggested;
	private Integer count;
	private Integer shareCount;
	private Integer addCount;
	private Integer sellCount;
	private Integer removeCount;
	private Date lastModification;
	private Date creationDate;

	public DeviceSuggestions() {
	}

	public DeviceSuggestions(int id, Device device, String codeSuggestion, String typeSuggestion) {
		this.id = id;
		this.device = device;
		this.codeSuggestion = codeSuggestion;
		this.typeSuggestion = typeSuggestion;
	}

	public DeviceSuggestions(int id, Device device, String codeSuggestion, String typeSuggestion, Integer countSuggested,
			Integer count, Date updateDate, Date creationDate) {
		this.id = id;
		this.device = device;
		this.codeSuggestion = codeSuggestion;
		this.typeSuggestion = typeSuggestion;
		this.countSuggested = countSuggested;
		this.count = count;
		this.lastModification = updateDate;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_device_suggestions_id")
	@SequenceGenerator(name="seq_device_suggestions_id", sequenceName="bolsos.seq_device_suggestions_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@Column(name = "code_suggestion", nullable = false, length = 50)
	public String getCodeSuggestion() {
		return this.codeSuggestion;
	}

	public void setCodeSuggestion(String codeSuggestion) {
		this.codeSuggestion = codeSuggestion;
	}

	@Column(name = "type_suggestion", nullable = false, length = 20)
	public String getTypeSuggestion() {
		return this.typeSuggestion;
	}

	public void setTypeSuggestion(String typeSuggestion) {
		this.typeSuggestion = typeSuggestion;
	}

	@Column(name = "count_suggested")
	public Integer getCountSuggested() {
		return this.countSuggested;
	}

	public void setCountSuggested(Integer countSuggested) {
		this.countSuggested = countSuggested;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}
	
	@Column(name = "add_count")
	public Integer getAddCount() {
		return this.addCount;
	}

	public void setAddCount(Integer addCount) {
		this.addCount = addCount;
	}
	
	@Column(name = "remove_count")
	public Integer getRemoveCount() {
		return this.removeCount;
	}

	public void setRemoveCount(Integer removeCount) {
		this.removeCount = removeCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modification", length = 29)
	public Date getLastModification() {
		return this.lastModification;
	}

	public void setLastModification(Date updateDate) {
		this.lastModification = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Override
	public void add(IDeviceAddable item) {
		IDeviceSuggestionable iDevice = (IDeviceSuggestionable)item;
		this.countSuggested = this.countSuggested + iDevice.getCountSuggested();
		this.count = this.count + iDevice.getCount();
		this.addCount = this.addCount + iDevice.getAddCount();
		this.removeCount = this.removeCount + iDevice.getRemoveCount();
		this.sellCount = this.sellCount + iDevice.getSellCount();
		this.shareCount = this.shareCount + iDevice.getShareCount();
		this.creationDate = CommonUtils.getNewestDate(this.creationDate, iDevice.getCreationDate());
		this.lastModification = CommonUtils.getNewestDate(this.lastModification, iDevice.getLastModification());
	}
	
	@Override
	public String toString(){
		return "Suggestion : " + getCodeSuggestion() + 
			   " ( " +  countSuggested +  count + ", " + addCount + ", " + 
						sellCount + ", " + shareCount + ", " +
					    removeCount + " )";
	}

	@Column(name = "sell_count")
	public Integer getSellCount() {
		return sellCount;
	}

	public void setSellCount(Integer sellCount) {
		this.sellCount = sellCount;
	}
	
	@Column(name = "share_count")
	public Integer getShareCount() {
		return shareCount;
	}

	public void setShareCount(Integer shareCount) {
		this.shareCount = shareCount;
	}
}
