package com.mg.model;

// Generated Oct 10, 2016 2:39:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.enums.UserActionParamType;

/**
 * MgUserActioParam generated by hbm2java
 */
@Entity
@Table(name = "mg_device_user_action_param", schema = "bolsos")
public class DeviceUserActionParam implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private DeviceProductHist deviceProductHist;
	private UserActionParamType param;
	private String paramValue;
	private Date creationDate;

	public DeviceUserActionParam() {
	}

	public DeviceUserActionParam(int id, DeviceProductHist deviceProductHist,
			UserActionParamType param, String paramValue) {
		this.id = id;
		this.deviceProductHist = deviceProductHist;
		this.param = param;
		this.paramValue = paramValue;
	}

	public DeviceUserActionParam(int id, DeviceProductHist deviceProductHist,
			UserActionParamType param, String paramValue, Date creationDate) {
		this.id = id;
		this.deviceProductHist = deviceProductHist;
		this.param = param;
		this.paramValue = paramValue;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_device_user_action_param_id")
	@SequenceGenerator(name="seq_device_user_action_param_id", sequenceName="bolsos.seq_device_user_action_param_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_hist_id", nullable = false)
	public DeviceProductHist getDeviceProductHist() {
		return this.deviceProductHist;
	}

	public void setDeviceProductHist(DeviceProductHist deviceProductHist) {
		this.deviceProductHist = deviceProductHist;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "param", nullable = false, length = 20)
	public UserActionParamType getParam() {
		return this.param;
	}

	public void setParam(UserActionParamType param) {
		this.param = param;
	}

	@Column(name = "param_value", nullable = false, length = 20)
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
