package com.mg.model;

// Generated Oct 13, 2016 4:27:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.datamining.interfaces.IDevice;

/**
 * DeviceSession generated by hbm2java
 */
@Entity
@Table(name = "mg_device_session", schema = "bolsos")
public class DeviceSession implements java.io.Serializable, IDevice {

	private static final long serialVersionUID = 1L;
	private int id;
	private Device device;
	private Long duration;
	private Date actionDate;
	private Date creationDate;

	public DeviceSession() {
	}

	public DeviceSession(int id, Device device) {
		this.id = id;
		this.device = device;
	}

	public DeviceSession(int id, Device device, Long duration,
			Date actionDate, Date creationDate) {
		this.id = id;
		this.device = device;
		this.duration = duration;
		this.actionDate = actionDate;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_device_session_id")
	@SequenceGenerator(name="seq_device_session_id", sequenceName="bolsos.seq_device_session_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@Column(name = "duration")
	public Long getDuration() {
		return this.duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "action_date", length = 29)
	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
