package com.mg.model;

// Generated Sep 18, 2016 9:01:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.datamining.interfaces.IDevice;
import com.mg.util.CommonUtils;

/**
 * DeviceUser generated by hbm2java
 */
@Entity
@Table(name = "mg_device_user", schema = "bolsos")
public class DeviceUser implements java.io.Serializable, BasicModel, IDevice {

	private static final long serialVersionUID = -5701816914058415049L;
	private int id;
	private Users users;
	private Device device;
	private Integer count;
	private Date creationDate;

	public DeviceUser() {
	}

	public DeviceUser(int id, Users users, Device device) {
		this.id = id;
		this.users = users;
		this.device = device;
	}

	public DeviceUser(int id, Users users, Device device,
			Date creationDate) {
		this.id = id;
		this.users = users;
		this.device = device;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_device_user_id")
	@SequenceGenerator(name="seq_device_user_id", sequenceName="bolsos.seq_device_user_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	
	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public void add(DeviceUser deviceUser1) {
		this.count = this.count + deviceUser1.getCount();
		this.creationDate = CommonUtils.getNewestDate(this.creationDate, deviceUser1.getCreationDate());
	}

}
