package com.mg.model;

// Generated Sep 18, 2016 9:01:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.entities.IDevice;
import com.mg.util.CommonUtils;

/**
 * DeviceComponent generated by hbm2java
 */
@Entity
@Table(name = "mg_device_component", schema = "bolsos")
public class DeviceComponent implements java.io.Serializable, BasicModel, IDevice {

	private static final long serialVersionUID = -8703658762277072277L;
	private int id;
	private Device device;
	private CustomComponentCollection customComponentCollection;
	private Integer count;
	private Integer shareCount;
	private Integer addCount;
	private Integer sellCount;
	private Integer removeCount;
	private Date lastModification;
	private Date creationDate;

	public DeviceComponent() {
	}

	public DeviceComponent(int id, Device device,
			CustomComponentCollection customComponentCollection) {
		this.id = id;
		this.device = device;
		this.customComponentCollection = customComponentCollection;
	}

	public DeviceComponent(int id, Device device,
			CustomComponentCollection customComponentCollection,
			Integer count, Integer addCount, Integer sellCount,
			Date lastModification, Date creationDate) {
		this.id = id;
		this.device = device;
		this.customComponentCollection = customComponentCollection;
		this.count = count;
		this.addCount = addCount;
		this.sellCount = sellCount;
		this.lastModification = lastModification;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_device_component_id")
	@SequenceGenerator(name="seq_device_component_id", sequenceName="bolsos.seq_device_component_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "component_id", nullable = false)
	public CustomComponentCollection getCustomComponentCollection() {
		return this.customComponentCollection;
	}

	public void setCustomComponentCollection(
			CustomComponentCollection customComponentCollection) {
		this.customComponentCollection = customComponentCollection;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "add_count")
	public Integer getAddCount() {
		return this.addCount;
	}

	public void setAddCount(Integer addCount) {
		this.addCount = addCount;
	}

	@Column(name = "sell_count")
	public Integer getSellCount() {
		return this.sellCount;
	}

	public void setSellCount(Integer sellCount) {
		this.sellCount = sellCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modification", length = 29)
	public Date getLastModification() {
		return this.lastModification;
	}

	public void setLastModification(Date lastModification) {
		this.lastModification = lastModification;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	
	@Column(name = "share_count")
	public Integer getShareCount() {
		return this.shareCount;
	}

	public void setShareCount(Integer shareCount) {
		this.shareCount = shareCount;
	}

	@Column(name = "remove_count")
	public Integer getRemoveCount() {
		return removeCount;
	}

	public void setRemoveCount(Integer removeCount) {
		this.removeCount = removeCount;
	}

	public void add(DeviceComponent deviceComponent1) {
		this.addCount = this.addCount + deviceComponent1.getAddCount();
		this.count = this.count + deviceComponent1.getCount();
		this.removeCount = this.removeCount + deviceComponent1.getRemoveCount();
		this.sellCount = this.sellCount + deviceComponent1.getSellCount();
		this.shareCount = this.shareCount + deviceComponent1.getShareCount();
		this.creationDate = CommonUtils.getNewestDate(this.creationDate, deviceComponent1.getCreationDate());
		this.lastModification = CommonUtils.getNewestDate(this.lastModification, deviceComponent1.getLastModification());
	}
	
	@Override
	public String toString(){
		return "CCCid : " + customComponentCollection.getId() + 
			   " ( " +  count + ", " + addCount + ", " + 
				sellCount + ", " + shareCount + ", " +
			    removeCount + " )";
	}

}
