package com.mg.model;

// Generated Sep 18, 2016 9:01:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.datamining.interfaces.IDevice;
import com.mg.enums.UserActionType;

/**
 * DeviceProductHist generated by hbm2java
 */
@Entity
@Table(name = "mg_device_product_hist", schema = "bolsos")
public class DeviceProductHist implements java.io.Serializable, BasicModel, IDevice {

	private static final long serialVersionUID = 243911412297448719L;
	private int id;
	private Device device;
	private Product product;
	private Long duration;
	private UserActionType userAction;
	private Date actionDate;
	private Date creationDate;
	private Set<DeviceUserActionParam> deviceUserActionParams = new HashSet<DeviceUserActionParam>(
			0);

	public DeviceProductHist() {
	}

	public DeviceProductHist(int id, Device device, Product product) {
		this.id = id;
		this.device = device;
		this.product = product;
	}

	public DeviceProductHist(int id, Device device, Product product,
			Long duration, Boolean added, Boolean sold, Date actionDate,
			Date creationDate) {
		this.id = id;
		this.device = device;
		this.product = product;
		this.duration = duration;
		this.actionDate = actionDate;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_device_product_hist_id")
	@SequenceGenerator(name="seq_device_product_hist_id", sequenceName="bolsos.seq_device_product_hist_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "duration")
	public Long getDuration() {
		return this.duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "action_date", length = 29)
	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceProductHist", cascade=CascadeType.ALL)
	public Set<DeviceUserActionParam> getUserActioParams() {
		return this.deviceUserActionParams;
	}

	public void setUserActioParams(Set<DeviceUserActionParam> deviceUserActionParams) {
		this.deviceUserActionParams = deviceUserActionParams;
	}
	
	@Enumerated(EnumType.STRING)
	@Column(name = "user_action", length = 10)
	public UserActionType getUserAction() {
		return this.userAction;
	}

	public void setUserAction(UserActionType userAction) {
		this.userAction = userAction;
	}

	@Override
	public String toString(){
		return "Productid : " + product.getId() + 
			   ", Action: " + userAction.name();
	}

}
