package com.mg.model;

// Generated 31-ene-2015 19:26:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.enums.ImageType;

/**
 * MgImage generated by hbm2java
 */
@Cacheable
@Entity
@Table(name = "mg_image", schema = "bolsos")
public class Image implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = -5959491795329436736L;
	private int id;
	private String name;
	private ImageType typeCode;
	private Integer size;
	private Integer height;
	private Integer width;
	private boolean large;
	private Date uploadDate;
	private int resolution;
	private int score;
	/**
	 * Contain the path to reach the file in server side.
	 */
	private String realName;
	private Date creationDate;
	private Set<CustomComponentText> customComponentTexts = new HashSet<CustomComponentText>(0);
	private Set<CustomComponentImage> customComponentImagesForImageId = new HashSet<CustomComponentImage>(0);
	
	public Image() {
	}

	public Image(int id, String name, ImageType typeCode, boolean large,
			Date uploadDate, int resolution, int score, String realName) {
		this.id = id;
		this.name = name;
		this.typeCode = typeCode;
		this.large = large;
		this.uploadDate = uploadDate;
		this.resolution = resolution;
		this.score = score;
		this.realName = realName;
	}

	public Image(int id, String name, ImageType typeCode, Integer size,
			Integer height, Integer width, boolean large, Date uploadDate,
			int resolution, int score, String realName, Date creationDate,
			Set<CustomComponentText> customComponentTexts,
			Set<CustomComponentImage> customComponentImagesForImageId) {
		this.id = id;
		this.name = name;
		this.typeCode = typeCode;
		this.size = size;
		this.height = height;
		this.width = width;
		this.large = large;
		this.uploadDate = uploadDate;
		this.resolution = resolution;
		this.score = score;
		this.realName = realName;
		this.creationDate = creationDate;
		this.customComponentTexts = customComponentTexts;
		this.customComponentImagesForImageId = customComponentImagesForImageId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_image_id")
	@SequenceGenerator(name="seq_image_id", sequenceName="bolsos.seq_image_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return How the file is named in the server.
	 */
	@Column(name = "name", nullable = false, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type_code", nullable = false, length = 10)
	@Enumerated(EnumType.STRING)
	public ImageType getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(ImageType typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "width")
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "large", nullable = false)
	public boolean isLarge() {
		return this.large;
	}

	public void setLarge(boolean large) {
		this.large = large;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upload_date", nullable = false, length = 29)
	public Date getUploadDate() {
		if(uploadDate == null){
			return new Date();
		}
		else {
			return this.uploadDate;
		}
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	@Column(name = "resolution", nullable = false)
	public int getResolution() {
		return this.resolution;
	}

	public void setResolution(int resolution) {
		this.resolution = resolution;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	/**
	 * @return The path where the image is in the server.
	 */
	@Column(name = "real_name", nullable = false, length = 120)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}
	
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imageByImageId", cascade = CascadeType.ALL)
	public Set<CustomComponentImage> getCustomComponentImagesForImageId() {
		return this.customComponentImagesForImageId;
	}

	public void setCustomComponentImagesForImageId(
			Set<CustomComponentImage> customComponentImagesForImageId) {
		this.customComponentImagesForImageId = customComponentImagesForImageId;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "image", cascade = CascadeType.ALL)
	public Set<CustomComponentText> getCustomComponentTexts() {
		return this.customComponentTexts;
	}

	public void setCustomComponentTexts(
			Set<CustomComponentText> customComponentTexts) {
		this.customComponentTexts = customComponentTexts;
	}
}
