package com.mg.model;

// Generated 07-may-2015 22:26:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgItemComponent generated by hbm2java
 */
@Entity
@Table(name = "mg_item_component", schema = "bolsos")
public class ItemComponent implements java.io.Serializable {

	private static final long serialVersionUID = -9199832156352326598L;
	private int id;
	private Item item;
	private CustomComponentImage customComponentImage;
	private CustomComponentCollection customComponentCollection;
	private Date creationDate;

	public ItemComponent() {
	}

	public ItemComponent(int id, Item item,
			CustomComponentImage customComponentImage,
			CustomComponentCollection customComponentCollection) {
		this.id = id;
		this.item = item;
		this.customComponentImage = customComponentImage;
		this.customComponentCollection = customComponentCollection;
	}

	public ItemComponent(int id, Item mgItem,
			CustomComponentImage customComponentImage,
			CustomComponentCollection customComponentCollection,
			Date creationDate) {
		this.id = id;
		this.item = item;
		this.customComponentImage = customComponentImage;
		this.customComponentCollection = customComponentCollection;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_item_component_id")
	@SequenceGenerator(name="seq_item_component_id", sequenceName="bolsos.seq_item_component_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "component_image_id", nullable = false)
	public CustomComponentImage getCustomComponentImage() {
		return this.customComponentImage;
	}

	public void setCustomComponentImage(
			CustomComponentImage customComponentImage) {
		this.customComponentImage = customComponentImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "component_collection_id", nullable = false)
	public CustomComponentCollection getCustomComponentCollection() {
		return this.customComponentCollection;
	}

	public void setCustomComponentCollection(
			CustomComponentCollection customComponentCollection) {
		this.customComponentCollection = customComponentCollection;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
