package com.mg.model;
// Generated Oct 22, 2017 5:40:12 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.annotation.FieldView;

/**
 * MgJobs generated by hbm2java
 */
@Entity
@Table(name = "mg_jobs", schema = "bolsos")
public class Jobs implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = -1329107003221675896L;
	@FieldView
	private int id;
	@FieldView
	private String name;
	@FieldView
	private String groupJob;
	@FieldView
	private String schedule;
	@FieldView
	private String value1;
	@FieldView
	private String value2;
	@FieldView
	private Date updateDate;
	@FieldView
	private Date creationDate;

	public Jobs() {
	}

	public Jobs(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Jobs(int id, String name, String groupJob, String schedule, String value1, String value2, Date updateDate,
			Date creationDate) {
		this.id = id;
		this.name = name;
		this.groupJob = groupJob;
		this.schedule = schedule;
		this.value1 = value1;
		this.value2 = value2;
		this.updateDate = updateDate;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_jobs_id")
	@SequenceGenerator(name="seq_jobs_id", sequenceName="bolsos.seq_jobs_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "group_job", length = 10)
	public String getGroupJob() {
		return this.groupJob;
	}

	public void setGroupJob(String groupJob) {
		this.groupJob = groupJob;
	}

	@Column(name = "schedule", length = 25)
	public String getSchedule() {
		return this.schedule;
	}

	public void setSchedule(String schedule) {
		this.schedule = schedule;
	}

	@Column(name = "value1", length = 25)
	public String getValue1() {
		return this.value1;
	}

	public void setValue1(String value1) {
		this.value1 = value1;
	}

	@Column(name = "value2", length = 25)
	public String getValue2() {
		return this.value2;
	}

	public void setValue2(String value2) {
		this.value2 = value2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
