package com.mg.model;

// Generated 09-sep-2015 23:54:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgLogs generated by hbm2java
 */
@Entity
@Table(name = "mg_logs", schema = "bolsos")
public class Logs implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = 1L;
	private int id;
	private Date creationDate;
	private String category;
	private String severity;
	private String message;
	private String serverName;

	public Logs() {
	}

	public Logs(int id) {
		this.id = id;
	}

	public Logs(int id, Date creationDate, String category, String severity,
			String message, String serverName) {
		this.id = id;
		this.creationDate = creationDate;
		this.category = category;
		this.severity = severity;
		this.message = message;
		this.serverName = serverName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_logs_id")
	@SequenceGenerator(name="seq_logs_id", sequenceName="bolsos.seq_logs_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "log_time", length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}
	
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "category", length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "severity", length = 5)
	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	@Column(name = "message", length = 2000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "server_name", length = 5)
	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

}
