package com.mg.model;

// Generated 07-may-2015 22:26:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.enums.Country;
import com.mg.enums.MethodShippingStatus;
import com.mg.util.currency.ICurrency;
import com.mg.util.translation.IBasicTranslation;

/**
 * MgMethodShipping generated by hbm2java
 */
@Entity
@Table(name = "mg_method_shipping", schema = "bolsos")
public class MethodShipping implements java.io.Serializable, BasicModel, ICurrency, IBasicTranslation {

	private static final long serialVersionUID = 2009122054868147531L;
	private int id;
	private String code;
	private Translation translationByNameTransId;
	private Translation translationByDescriptionTransId;
	private Price price;
	private Date creationDate;
	private Country country;
	private MethodShippingStatus statusCode;
	private Set<ShoppingCart> shoppingCarts = new HashSet<ShoppingCart>(0);

	public MethodShipping() {
	}

	public MethodShipping(int id, String code, Translation translationByDescriptionTransId,
			Price price) {
		this.id = id;
		this.code = code;
		this.translationByDescriptionTransId = translationByDescriptionTransId;
		this.price = price;
	}

	public MethodShipping(int id, String code, Translation translationByDescriptionTransId,
			Price price, Date creationDate, Set<ShoppingCart> shoppingCarts) {
		this.id = id;
		this.code = code;
		this.translationByDescriptionTransId = translationByDescriptionTransId;
		this.price = price;
		this.creationDate = creationDate;
		this.shoppingCarts = shoppingCarts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_method_shipping_id")
	@SequenceGenerator(name="seq_method_shipping_id", sequenceName="bolsos.seq_method_shipping_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "description_trans_id")
	public Translation getTranslationByDescriptionTransId() {
		return translationByDescriptionTransId;
	}

	public void setTranslationByDescriptionTransId(
			Translation translationByDescriptionTransId) {
		this.translationByDescriptionTransId = translationByDescriptionTransId;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "price")
	public Price getPrice() {
		return this.price;
	}

	public void setPrice(Price price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "methodShipping")
	public Set<ShoppingCart> getShoppingCarts() {
		return this.shoppingCarts;
	}

	public void setShoppingCarts(Set<ShoppingCart> shoppingCarts) {
		this.shoppingCarts = shoppingCarts;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "name_trans_id")
	public Translation getTranslationByNameTransId() {
		return translationByNameTransId;
	}

	public void setTranslationByNameTransId(Translation translationByNameTransId) {
		this.translationByNameTransId = translationByNameTransId;
	}
	
	@Column(name = "country", nullable = false, length = 225)
	@Enumerated(EnumType.STRING)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}
	
	@Column(name = "status_code", nullable = false, length = 10)
	@Enumerated(EnumType.STRING)
	public MethodShippingStatus getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(MethodShippingStatus statusCode) {
		this.statusCode = statusCode;
	}

}
