package com.mg.model;

// Generated Feb 18, 2017 11:33:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgPaypal generated by hbm2java
 */
@Entity
@Table(name = "mg_paypal", schema = "bolsos")
public class Paypal implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = 1L;
	private int id;
	private ShoppingCart shoppingCart;
	private String token;
	private String payerid;
	private String correlationid;
	private String errorcode;
	private String ack;
	private String severitycode;
	private String shormessage;
	private String longmessage;
	private Date updateDate;
	private Date creationDate;

	public Paypal() {
	}

	public Paypal(int id, ShoppingCart shoppingCart, String token) {
		this.id = id;
		this.shoppingCart = shoppingCart;
		this.token = token;
	}

	public Paypal(int id, ShoppingCart shoppingCart, String token,
			String payerid, String correlationid, Date updateDate,
			Date creationDate) {
		this.id = id;
		this.shoppingCart = shoppingCart;
		this.token = token;
		this.payerid = payerid;
		this.correlationid = correlationid;
		this.updateDate = updateDate;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_paypal_id")
	@SequenceGenerator(name="seq_paypal_id", sequenceName="bolsos.seq_paypal_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reference", referencedColumnName="reference", nullable = false)
	public ShoppingCart getShoppingCart() {
		return this.shoppingCart;
	}

	public void setShoppingCart(ShoppingCart shoppingCart) {
		this.shoppingCart = shoppingCart;
	}

	@Column(name = "token", nullable = false, length = 25)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "payerid", length = 15)
	public String getPayerid() {
		return this.payerid;
	}

	public void setPayerid(String payerid) {
		this.payerid = payerid;
	}

	@Column(name = "correlationid", length = 25)
	public String getCorrelationid() {
		return this.correlationid;
	}

	public void setCorrelationid(String correlationid) {
		this.correlationid = correlationid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "errorcode", length = 10)
	public String getErrorcode() {
		return errorcode;
	}

	public void setErrorcode(String errorcode) {
		this.errorcode = errorcode;
	}

	@Column(name = "ack", length = 15)
	public String getAck() {
		return ack;
	}

	public void setAck(String ack) {
		this.ack = ack;
	}

	@Column(name = "severitycode", length = 15)
	public String getSeveritycode() {
		return severitycode;
	}

	public void setSeveritycode(String severitycode) {
		this.severitycode = severitycode;
	}

	@Column(name = "shormessage", length = 150)
	public String getShormessage() {
		return shormessage;
	}

	public void setShormessage(String shormessage) {
		this.shormessage = shormessage;
	}

	@Column(name = "longmessage", length = 255)
	public String getLongmessage() {
		return longmessage;
	}

	public void setLongmessage(String longmessage) {
		this.longmessage = longmessage;
	}

}
