package com.mg.model;

// Generated 18-sep-2015 22:47:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgPrice generated by hbm2java
 */
@Entity
@Table(name = "mg_price", schema = "bolsos")
public class Price implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = -3586308369301567624L;
	private int id;
	private Date creationDate;
	private Set<PriceEntry> priceEntries = new HashSet<PriceEntry>(0);
	private Product product = new Product();
	private MethodShipping methodShipping = new MethodShipping();

	public Price() {
	}

	public Price(int id) {
		this.id = id;
	}

	public Price(int id, Date creationDate, Set<PriceEntry> priceEntries,
			Product product, MethodShipping methodShipping) {
		this.id = id;
		this.creationDate = creationDate;
		this.priceEntries = priceEntries;
		this.product = product;
		this.methodShipping = methodShipping;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_price_id")
	@SequenceGenerator(name="seq_price_id", sequenceName="bolsos.seq_price_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "price", cascade=CascadeType.ALL)
	public Set<PriceEntry> getPriceEntries() {
		return this.priceEntries;
	}

	public void setPriceEntries(Set<PriceEntry> priceEntries) {
		this.priceEntries = priceEntries;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "price")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "price")
	public MethodShipping getMethodShipping() {
		return this.methodShipping;
	}

	public void setMethodShipping(MethodShipping methodShipping) {
		this.methodShipping = methodShipping;
	}

}
