package com.mg.model;

// Generated 18-sep-2015 22:47:46 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgPriceEntry generated by hbm2java
 */
@Entity
@Table(name = "mg_price_entry", schema = "bolsos")
public class PriceEntry implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = -2024599001367699355L;
	private int id;
	private Price price;
	private BigDecimal priceCurrency;
	private BigDecimal discount;
	private String currency;
	private Date creationDate;

	public PriceEntry() {
	}

	public PriceEntry(int id, Price price, BigDecimal priceCurrency, String currency) {
		this.id = id;
		this.price = price;
		this.priceCurrency = priceCurrency;
		this.currency = currency;
	}

	public PriceEntry(int id, Price price, BigDecimal priceCurrency, String currency,
			Date creationDate) {
		this.id = id;
		this.price = price;
		this.priceCurrency = priceCurrency;
		this.currency = currency;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_price_entry_id")
	@SequenceGenerator(name="seq_price_entry_id", sequenceName="bolsos.seq_price_entry_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "price_id", nullable = false)
	public Price getPrice() {
		return this.price;
	}

	public void setPrice(Price price) {
		this.price = price;
	}

	@Column(name = "price", nullable = false, precision = 10, scale = 2)
	public BigDecimal getPriceCurrency() {
		return this.priceCurrency;
	}

	public void setPriceCurrency(BigDecimal priceCurrency) {
		this.priceCurrency = priceCurrency;
	}

	@Column(name = "currency", nullable = false, length = 5)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "discount", precision = 10, scale = 2)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

}
