package com.mg.model;

// Generated 07-may-2015 22:26:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgProductTag generated by hbm2java
 */
@Entity
@Table(name = "mg_product_tag", schema = "bolsos")
public class ProductTag implements java.io.Serializable {

	private static final long serialVersionUID = -3657649375964573574L;
	private int id;
	private Product product;
	private String tag;
	private Date creationDate;

	public ProductTag() {
	}

	public ProductTag(int id, Product product) {
		this.id = id;
		this.product = product;
	}

	public ProductTag(int id, Product product, String tag,
			Date creationDate) {
		this.id = id;
		this.product = product;
		this.tag = tag;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
