package com.mg.model;

// Generated 07-may-2015 22:26:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MgProductTag generated by hbm2java
 */
@Entity
@Table(name = "mg_product_order", schema = "bolsos")
public class ProductOrder implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = -3657649375964573574L;
	private int id;
	private Product product;
	private Integer order;
	private Date creationDate;

	public ProductOrder() {
	}

	public ProductOrder(int id, Product product) {
		this.id = id;
		this.product = product;
	}

	public ProductOrder(int id, Product product, Integer order,
			Date creationDate) {
		this.id = id;
		this.product = product;
		this.order = order;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_product_order_id")
	@SequenceGenerator(name="seq_product_order_id", sequenceName="bolsos.seq_product_order_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "product_order")
	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
