package com.mg.model;
// Generated Jan 29, 2019 9:02:24 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductData generated by hbm2java
 */
@Entity
@Table(name = "mg_product_data", schema = "bolsos")
public class ProductData implements java.io.Serializable, BasicModel{
	
	private static final long serialVersionUID = 1L;
	private int id;
	private Product product;
	private String cluster;
	private Date creationDate;

	public ProductData() {
	}

	public ProductData(Product product, String cluster) {
		this.product = product;
		this.cluster = cluster;
	}
	
	public ProductData(int id, Product product, String cluster) {
		this.id = id;
		this.product = product;
		this.cluster = cluster;
	}

	public ProductData(int id, Product product, String cluster, Date creationDate) {
		this.id = id;
		this.product = product;
		this.cluster = cluster;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_product_data_id")
	@SequenceGenerator(name = "seq_product_data_id", sequenceName = "bolsos.seq_product_data_id", initialValue = 1, allocationSize = 1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "cluster", nullable = false, length = 20)
	public String getCluster() {
		return this.cluster;
	}

	public void setCluster(String cluster) {
		this.cluster = cluster;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
