package com.mg.model;
// Generated Oct 8, 2018 10:47:08 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductData generated by hbm2java
 */
@Entity
@Table(name = "mg_product_data", schema = "bolsos")
public class ProductData implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ProductDataId id;
	private Product productByProductId;
	private Product productById;
	private String cluster;
	private Date creationDate;

	public ProductData() {
	}

	public ProductData(ProductDataId id, Product productByProductId, Product productById) {
		this.id = id;
		this.productByProductId = productByProductId;
		this.productById = productById;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
	public ProductDataId getId() {
		return this.id;
	}

	public void setId(ProductDataId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProductByProductId() {
		return this.productByProductId;
	}

	public void setProductByProductId(Product productByProductId) {
		this.productByProductId = productByProductId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false, insertable = false, updatable = false)
	public Product getProductById() {
		return this.productById;
	}

	public void setProductById(Product productById) {
		this.productById = productById;
	}
	
	@Column(name = "cluster", nullable = false, length = 20)
	public String getCluster() {
		return this.cluster;
	}

	public void setCluster(String cluster) {
		this.cluster = cluster;
	}

	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
