package com.mg.model;
// Generated Oct 8, 2018 10:47:08 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MProductDataId generated by hbm2java
 */
@Embeddable
public class ProductDataId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private int productId;

	public ProductDataId() {
	}

	public ProductDataId(int id, int productId) {
		this.id = id;
		this.productId = productId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductDataId))
			return false;
		ProductDataId castOther = (ProductDataId) other;

		return ( this.getId() == castOther.getId()) && (this.getProductId() == castOther.getProductId() );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
