package com.mg.model;
// Generated Feb 12, 2019 4:47:40 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Suggestions generated by hbm2java
 */
@Entity
@Table(name = "mg_suggestions", schema = "bolsos")
@DynamicUpdate
public class Suggestions implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = 1L;
	private int id;
	private Product product;
	private Users users;
	private String suggestion;
	private String sessionGuid;
	private Integer count;
	private Date creationDate;
//	private Item item;

	public Suggestions() {
	}

	public Suggestions(int id, Product product, String sessionGuid) {
		this.id = id;
		this.product = product;
		this.sessionGuid = sessionGuid;
	}

	public Suggestions(int id, Product product, Users users, String suggestion, String sessionGuid,
			Integer count, Date creationDate) {
		this.id = id;
		this.product = product;
		this.users = users;
		this.suggestion = suggestion;
		this.sessionGuid = sessionGuid;
		this.count = count;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_suggestions_id")
	@SequenceGenerator(name = "seq_suggestions_id", sequenceName = "bolsos.seq_suggestions_id", initialValue = 1, allocationSize = 1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "suggestion", length = 25)
	public String getSuggestion() {
		return this.suggestion;
	}

	public void setSuggestion(String suggestion) {
		this.suggestion = suggestion;
	}

	@Column(name = "session_guid", nullable = false, length = 32)
	public String getSessionGuid() {
		return this.sessionGuid;
	}

	public void setSessionGuid(String sessionGuid) {
		this.sessionGuid = sessionGuid;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

//	@Id @ManyToOne(fetch = FetchType.LAZY)
//	//@JoinColumn(name = "device_id", nullable = false)
//	@JoinColumn(name = "suggestion",referencedColumnName = "name_image", insertable=false, updatable=false)
//	public Item getItem() {
//		return this.item;
//	}
//
//	public void setItem(Item item) {
//		this.item = item;
//	}

}
