package com.mg.model;

// Generated 03-oct-2015 1:21:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mg.enums.PaymentCVX;
import com.mg.enums.PaymentCodeReturn;
import com.mg.enums.PaymentFraudCode;
import com.mg.enums.PaymentMethodType;

/**
 * MgTransaction generated by hbm2java
 */
@Entity
@Table(name = "mg_transaction", schema = "bolsos")
public class Transaction implements java.io.Serializable, BasicModel {

	private static final long serialVersionUID = -1954038350546938200L;
	private int id;
	private ShoppingCart shoppingCart;
	private String tpe;
	private Date purchaseDate;
	private String mac;
	private String montant;
	private String texteLibre;
	private PaymentCodeReturn codeRetour;
	private PaymentCVX cvx;
	private String vld;
	private PaymentMethodType brand;
	private String status3ds;
	private String originecb;
	private String bincb;
	private String hpancb;
	private String ipclient;
	private String originetr;
	private PaymentFraudCode filtragecause;
	private String cbenregistree;
	private String cbmasquee;
	private Date creationDate;
	private Set<ShoppingCart> shoppingCarts = new HashSet<ShoppingCart>(0);

	public Transaction() {
	}

	public Transaction(int id, ShoppingCart shoppingCart, String tpe,
			String mac, String montant, PaymentCodeReturn codeRetour) {
		this.id = id;
		this.shoppingCart = shoppingCart;
		this.tpe = tpe;
		this.mac = mac;
		this.montant = montant;
		this.codeRetour = codeRetour;
	}

	public Transaction(int id, ShoppingCart shoppingCart, String tpe,
			Date purchaseDate, String mac, String montant, String texteLibre,
			PaymentCodeReturn codeRetour, PaymentCVX cvx, String vld, PaymentMethodType brand,
			String status3ds, String originecb, String bincb, String hpancb,
			String ipclient, String originetr, PaymentFraudCode filtragecause,
			String cbenregistree, String cbmasquee, Date creationDate,
			Set<ShoppingCart> shoppingCarts) {
		this.id = id;
		this.shoppingCart = shoppingCart;
		this.tpe = tpe;
		this.purchaseDate = purchaseDate;
		this.mac = mac;
		this.montant = montant;
		this.texteLibre = texteLibre;
		this.codeRetour = codeRetour;
		this.cvx = cvx;
		this.vld = vld;
		this.brand = brand;
		this.status3ds = status3ds;
		this.originecb = originecb;
		this.bincb = bincb;
		this.hpancb = hpancb;
		this.ipclient = ipclient;
		this.originetr = originetr;
		this.filtragecause = filtragecause;
		this.cbenregistree = cbenregistree;
		this.cbmasquee = cbmasquee;
		this.creationDate = creationDate;
		this.shoppingCarts = shoppingCarts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_transaction_id")
	@SequenceGenerator(name="seq_transaction_id", sequenceName="bolsos.seq_transaction_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade={CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinColumn(name = "reference", referencedColumnName="reference", nullable = false)
	public ShoppingCart getShoppingCart() {
		return this.shoppingCart;
	}

	public void setShoppingCart(ShoppingCart shoppingCart) {
		this.shoppingCart = shoppingCart;
	}

	@Column(name = "tpe", nullable = false, length = 15)
	public String getTpe() {
		return this.tpe;
	}

	public void setTpe(String tpe) {
		this.tpe = tpe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_date", length = 29)
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	@Column(name = "mac", nullable = false, length = 100)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	@Column(name = "montant", nullable = false, length = 15)
	public String getMontant() {
		return this.montant;
	}

	public void setMontant(String montant) {
		this.montant = montant;
	}

	@Column(name = "texte_libre")
	public String getTexteLibre() {
		return this.texteLibre;
	}

	public void setTexteLibre(String texteLibre) {
		this.texteLibre = texteLibre;
	}

	@Column(name = "code_retour", nullable = false, length = 10)
	@Enumerated(EnumType.STRING)
	public PaymentCodeReturn getCodeRetour() {
		return this.codeRetour;
	}

	public void setCodeRetour(PaymentCodeReturn codeRetour) {
		this.codeRetour = codeRetour;
	}

	@Column(name = "cvx", length = 20)
	@Enumerated(EnumType.STRING)
	public PaymentCVX getCvx() {
		return this.cvx;
	}

	public void setCvx(PaymentCVX cvx) {
		this.cvx = cvx;
	}

	@Column(name = "vld", length = 10)
	public String getVld() {
		return this.vld;
	}

	public void setVld(String vld) {
		this.vld = vld;
	}

	@Column(name = "brand", length = 20)
	@Enumerated(EnumType.STRING)
	public PaymentMethodType getBrand() {
		return this.brand;
	}

	public void setBrand(PaymentMethodType brand) {
		this.brand = brand;
	}

	@Column(name = "status3ds", length = 3)
	public String getStatus3ds() {
		return this.status3ds;
	}

	public void setStatus3ds(String status3ds) {
		this.status3ds = status3ds;
	}

	@Column(name = "originecb", length = 10)
	public String getOriginecb() {
		return this.originecb;
	}

	public void setOriginecb(String originecb) {
		this.originecb = originecb;
	}

	@Column(name = "bincb", length = 20)
	public String getBincb() {
		return this.bincb;
	}

	public void setBincb(String bincb) {
		this.bincb = bincb;
	}

	@Column(name = "hpancb", length = 100)
	public String getHpancb() {
		return this.hpancb;
	}

	public void setHpancb(String hpancb) {
		this.hpancb = hpancb;
	}

	@Column(name = "ipclient", length = 20)
	public String getIpclient() {
		return this.ipclient;
	}

	public void setIpclient(String ipclient) {
		this.ipclient = ipclient;
	}

	@Column(name = "originetr", length = 10)
	public String getOriginetr() {
		return this.originetr;
	}

	public void setOriginetr(String originetr) {
		this.originetr = originetr;
	}

	@Column(name = "filtragecause", length = 2)
	@Enumerated(EnumType.STRING)
	public PaymentFraudCode getFiltragecause() {
		return this.filtragecause;
	}

	public void setFiltragecause(PaymentFraudCode filtragecause) {
		this.filtragecause = filtragecause;
	}

	@Column(name = "cbenregistree", length = 1)
	public String getCbenregistree() {
		return this.cbenregistree;
	}

	public void setCbenregistree(String cbenregistree) {
		this.cbenregistree = cbenregistree;
	}

	@Column(name = "cbmasquee", length = 16)
	public String getCbmasquee() {
		return this.cbmasquee;
	}

	public void setCbmasquee(String cbmasquee) {
		this.cbmasquee = cbmasquee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaction")
	public Set<ShoppingCart> getShoppingCarts() {
		return this.shoppingCarts;
	}

	public void setShoppingCarts(Set<ShoppingCart> shoppingCarts) {
		this.shoppingCarts = shoppingCarts;
	}

}
