package com.mg.model;

// Generated 31-ene-2015 19:26:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MgTranslationEntry generated by hbm2java
 */
@Entity
@Table(name = "mg_translation_entry", schema = "bolsos", uniqueConstraints = {
		@UniqueConstraint(columnNames = "id") })
public class TranslationEntry implements java.io.Serializable, BasicModel{

	/**
	 * 
	 */
	private static final long serialVersionUID = -99659761485702888L;
	private int id;
	private Translation translation;
	private String langCode;
	private String text;
	private Date creationDate;

	public TranslationEntry() {
	}

	public TranslationEntry(int id, Translation translation,
			String langCode, String text, Date creationDate) {
		this.id = id;
		this.translation = translation;
		this.langCode = langCode;
		this.text = text;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_translation_entry_id")
	@SequenceGenerator(name="seq_translation_entry_id", sequenceName="bolsos.seq_translation_entry_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trans_id", nullable = false)
	public Translation getTranslation() {
		return this.translation;
	}

	public void setTranslation(Translation translation) {
		this.translation = translation;
	}

	@Column(name = "lang_code", nullable = false, length = 3)
	public String getLangCode() {
		return this.langCode;
	}

	public void setLangCode(String langCode) {
		this.langCode = langCode;
	}

	@Column(name = "text", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(creationDate==null){
			return( new Date());
		}
		else {
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
