package com.mg.model;

// Generated 31-ene-2015 19:26:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.BatchSize;

import com.mg.enums.UserStatus;
import com.mg.enums.UserType;

/**
 * MgUsers generated by hbm2java
 */
@Entity
@Table(name = "mg_users", schema = "bolsos")
public class Users implements java.io.Serializable, BasicModel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7414334882410975397L;
	private int id;
	private String firstName;
	private String lastName;
	private String phone;
	private String login;
	private UserType typeCode;
	private UserStatus statusCode;
	private String password;
	private String email;
	private Date lastLoginDate;
	private Boolean active;
	private String lang;
	private Date creationDate;
	private Set<UserAddress> userAddresses = new HashSet<UserAddress>(0);
	private Set<ShoppingCart> shoppingCarts = new HashSet<ShoppingCart>(0);

	public Users() {
	}

	public Users(int id){
		this.id = id;
	}
			
	public Users(int id, String login, String firstName, String lastName, String phone, UserType typeCode, UserStatus statusCode,
			String password, String email, Date creationDate) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.login = login;
		this.typeCode = typeCode;
		this.statusCode = statusCode;
		this.password = password;
		this.email = email;
		this.creationDate = creationDate;
	}

	public Users(int id, String login, String firstName, String lastName, String phone, UserType typeCode, UserStatus statusCode,
			String password, String email, Date lastLoginDate, Boolean active,
			Date creationDate, Set<UserAddress> userAddresses) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.login = login;
		this.typeCode = typeCode;
		this.statusCode = statusCode;
		this.password = password;
		this.email = email;
		this.lastLoginDate = lastLoginDate;
		this.active = active;
		this.creationDate = creationDate;
		this.userAddresses = userAddresses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_user_id")
	@SequenceGenerator(name="seq_user_id", sequenceName="bolsos.seq_user_id", initialValue=1, allocationSize= 1 )
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "login", nullable = false, length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "type_code", nullable = false, length = 10)
	@Enumerated(EnumType.STRING)
	public UserType getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(UserType typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "status_code", nullable = false, length = 10)
	@Enumerated(EnumType.STRING)
	public UserStatus getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(UserStatus statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "password", nullable = false, length = 500)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false, length = 320)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_date", length = 29)
	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 29)
	public Date getCreationDate() {
		if(this.creationDate == null){
			return new Date();
		}
		else{
			return this.creationDate;
		}
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	//@JoinColumn( name="id")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users", cascade=CascadeType.ALL)
	@BatchSize(size=50)
	public Set<UserAddress> getUserAddresses() {
		return this.userAddresses;
	}

	public void setUserAddresses(Set<UserAddress> userAddresses) {
		this.userAddresses = userAddresses;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<ShoppingCart> getShoppingCarts() {
		return this.shoppingCarts;
	}

	public void setShoppingCarts(Set<ShoppingCart> shoppingCarts) {
		this.shoppingCarts = shoppingCarts;
	}

	@Column(name = "first_name", nullable = false, length = 50)
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 50)
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "telephone", nullable = false, length = 50)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "lang", length = 3)
	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}


}
